# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  enable-dynamic-allocation:
    type: boolean
    description: |
      Enable dynamic allocation of pods for autoscaling Spark jobs.
      Is equivalent to the following Spark configurations:

      spark.dynamicAllocation.enabled=true
      spark.dynamicAllocation.shuffleTracking.enabled=true
      spark.dynamicAllocation.minExecutors=1

    default: false
